### ISSUE TITLE
E/PropertyValuesHolder﹕ Couldn't find setter/getter for property degree with value type float

### ISSUE THREAD

**Issue by aritraroy** [asyl/ArcAnimator#10]
I am getting this error every time. How can I solve this?

**Comment by asyl** [comment]
Can you share this error widely or show any screens from logcat?

**Comment by aritraroy** [comment]
Actually, there is nothing more to show wisely. I just get that single line of error and nothing related to that anywhere in LogCat, otherwise I would have been more than happy to post the LogCat.

**Comment by asyl** [comment]
I'm sorry for word 'wisely', this is my typo, I meant 'widely'. Sorry

**Comment by aritraroy** [comment]
No, not a problem. I can understand. :-) Btw, any idea on how to solve this problem? I also tried changing the ObjectAnimator.ofFloat to ObjectAnimator.ofInt, but still the same error.

**Comment by giolin** [comment]
Got exactly the same issue here
