### ISSUE TITLE
Error:A problem occurred configuring project ':arcsample'.

### ISSUE THREAD

**Issue by audiebant** [asyl/ArcAnimator#6]
Error:A problem occurred configuring project ':arcsample'.

> Could not resolve all dependencies for configuration ':arcsample:_debugCompile'.
> Could not find com.github.ozodrukh:CircularReveal:1.0.4.
>      Searched in the following locations:
>          https://jcenter.bintray.com/com/github/ozodrukh/CircularReveal/1.0.4/CircularReveal-1.0.4.pom
>          https://jcenter.bintray.com/com/github/ozodrukh/CircularReveal/1.0.4/CircularReveal-1.0.4.aar

**Comment by asyl** [comment]
add remote maven url

```
repositories {
    maven {
        url "https://jitpack.io"
    }
}
```

then add a library dependency

```
dependencies {
    compile 'com.github.ozodrukh:CircularReveal:(latest-release)@aar'
}
```
